# Generated by Django 4.1.7 on 2023-03-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Clothes',
        ),
    ]
