# Generated by Django 4.1.7 on 2023-04-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_clothes_options_clothes_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clothes')),
            ],
        ),
    ]
